import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import { Josefin_Sans, Inter } from "next/font/google";
import "./globals.css";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Dominic Hart",
  description: "Generated by create next app",
  icons: {
      icon: "images/icons/HSS-logo.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${josefin.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col z-0">
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
